---
dist: trusty
sudo: required

language: python
python: "2.7"

language: php
php:
#  - '5.4'
  - '5.5'
#  - '5.6'
#  - '7.0'
#  - hhvm
#  - nightly

env:
#  - SITE=test.yml
#  - ANSIBLE_VERSION=1.6
#  - ANSIBLE_VERSION=1.7
#  - ANSIBLE_VERSION=1.8
#  - ANSIBLE_VERSION=1.9 -- why is this broken? Vagrant on Valkyrie wants Ansible 1.9
  - ANSIBLE_VERSION=2.0
  - ANSIBLE_VERSION=2.0.0.1

#notifications:
#  slack:
#    secure: "AIKMmxzYL6xbpY4uN8BxhXDs+Em/PpVHy4OZcnal6+jBKW5xNNPOXiZ1KyZuaC40sYzW43CC3xUYS8KxQ1JvAvkZoGQp6XgLBV5xePNd5vVx1+v/vwzCOSRaWU9wse/ROYYxHJCZ4Hbf5w+k0K2SGQwtKqlzNwcfL8OcBmattdA="

before_install:
  - sudo apt-get update -qq
#  - DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -yq
  - sudo apt-get install curl -yq
  # Avoid harmless (but annoying) warnings.
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs
  # Completely remove mysql
  - sudo apt-get remove -y --purge mysql-server mysql-client mysql-common
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo rm -rf /root/.my.cnf

install:
  # Install Ansible from sources.
  - curl https://raw.githubusercontent.com/GetValkyrie/ansible-bootstrap/master/install-ansible.sh|sudo /bin/sh

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install required dependencies.
  - ansible-galaxy install http://github.com/geerlingguy/ansible-role-mysql,,geerlingguy.mysql
  - ansible-galaxy install http://github.com/geerlingguy/ansible-role-java,,geerlingguy.java
  - ansible-galaxy install http://github.com/ErgonLogicEnterprises/ansible-role-aegir.git,,getvalkyrie.aegir
  - ansible-galaxy install http://github.com/ErgonLogicEnterprises/ansible-role-drulenium.git,,getvalkyrie.drulenium
  - ansible-galaxy install http://github.com/ErgonLogicEnterprises/ansible-role-selenium.git,,getvalkyrie.selenium
  - ansible-galaxy install http://github.com/ErgonLogicEnterprises/ansible-role-drush.git,,getvalkyrie.drush

script:
  # Check the role/playbook's syntax.
  - "sudo ansible-playbook -i tests/inventory tests/test.yml --syntax-check --sudo"

  # Run the role/playbook with ansible-playbook.
  - "sudo ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    sudo ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check if Aegir is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir
