---
# tasks file for ansible-role-aegir3drulenium

- name: GIT | Ensure GIT CLONE of Drupal Projects
  git:
    repo: "https://git.drupal.org/project/{{ item.project_name }}.git"
    dest: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/all/modules/{{ item.project_name }}"
#    depth: 1 # speeds things up
    version: "{{ item.git_repo_version }}"
    update: "{{ item.git_repo_update }}"
  register: drulenium_module_git_repos_registered
  with_items: "drulenium_module_git_repos"
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  when: drulenium_module_git_install
  tags: [git, download]

- debug:
    var: drulenium_module_git_repos_registered
    tags: [git, download, debug, drulenium]

- name: Check if Aegir Drulenium modules are enabled
  shell: "drush @hm pm-info --fields=status --format=list {{ item.project_name }} | egrep 'disabled|not installed'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: drulenium_modules_enabled
  with_items: drulenium_module_git_repos
  changed_when: False
  failed_when: False
  ignore_errors: yes

- debug:
    var: drulenium_modules_enabled
    tags: [git, download, debug, drulenium_modules]

- name: Enable Aegir Drulenium modules
  command: "drush @hm --yes en {{ item.1 }} --no-verify --strict=0"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  with_indexed_items: drulenium_modules
  when: "drulenium_modules_enabled.results[{{ item.0 }}].rc == 0"
  notify: Verify Aegir front-end

- debug:
    var: drulenium_modules_enabled
    tags: [git, download, debug, drulenium]

- name: GIT | Ensure GIT CLONE of PHP Selenium Web Driver
  git:
    repo: "{{ php_webdriver_repo }}"
    dest: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/all/libraries/{{ php_webdriver_dest }}"
    version: "{{ php_webdriver_version }}"
    update: "{{ php_webdriver_update }}"
  register: php_webdriver
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  tags: [git, download, selenium, selenium_webdriver]

- debug:
    var: drulenium_module_git_repos
    tags: [git, download, debug, drulenium]

- name: Drush | clear cache - drush cc all
  sudo: True
  sudo_user: "{{ aegir_user }}"
  command: drush cc all
  changed_when: False
  tags: [drush]

- name: drush @hostmaster hosting-tasks --debug
  sudo: True
  sudo_user: "{{ aegir_user }}"
  changed_when: False
  command: drush @hostmaster hosting-tasks --debug
