---
# tasks file for ansible-role-aegir3drulenium
- name: Drush Download Hosting Drulenium Dependencies Diff and Libraries
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: drush @hostmaster dl diff libraries -y
  register: drush_dl_drulenium_dependencies

- debug:
    var: drush_dl_drulenium_dependencies



- name: Enable Diff Number Libraries via Drush
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: drush @hostmaster en diff number libraries taxonomy -y
  register: drush_dl_drulenium_dependencies_enabled

- debug:
    var: drush_dl_drulenium_dependencies_enabled

#- name: Check
#  stat: path=/etc/shorewall/rules
#  register: shorewall_rules

#- name: Get PHP Web Driver
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  shell: wget https://github.com/facebook/php-webdriver/archive/master.zip -O /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/master.zip
#  register: drush_wget_php_web_driver

- debug:
    var: drush_wget_php_web_driver

- unarchive: src=https://github.com/facebook/php-webdriver/archive/master.zip dest=/var/aegir/hostmaster-7.x-3.x/sites/all/libraries copy=no

#- name: Unzip PHP Web Driver
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  shell: unzip -d /var/aegir/hostmaster-7.x-3.x/sites/all/libraries /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/master.zip
#  ignore_errors: yes

- name: Check PHP Web Driver
  stat: path=/var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver
  register: check_web_driver

#- name: Move PHP Web Driver
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: move_php_web_driver
#  shell: mv /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/php-webdriver-master /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver
#  ignore_errors: yes


- name: Move php-webdriver-master to selenium_webdriver
  sudo: True
  sudo_user: "{{ aegir_user }}"
  command: creates="/var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver" mv /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/php-webdriver-master/ /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver
#  when: foo_stat.stat.exists

  #when: check_web_driver.rc != 1

#- name: Switch to aegir and download Hosting Drulenium
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster dl drulenium-1.0-beta22 -y

## vset Drulenium settings for Ubuntu 14 or via Feature?

#- name: Switch to aegir and download Hosting Drulenium via become_user
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster dl hosting_drulenium-3.0-alpha2 -y

#- name: Switch to aegir and enable Drulenium
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster en drulenium -y

#- name: Switch to aegir and enable Hosting Drulenium
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster en hosting_drulenium -y

#- name: clear cache - drush cc drush
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush cc drush

#- name: clear cache - drush cc all
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
#  shell: drush cc all

#- name: drush @hostmaster hosting-tasks --debug
#  sudo: True
#  sudo_user: "{{ aegir_user }}"

#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster hosting-tasks --debug
