---
# tasks file for ansible-role-aegir3drulenium
- name: Drush Download Hosting Drulenium Dependencies Diff and Libraries
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: drush @hostmaster dl diff libraries -y
  register: drush_dl_drulenium_dependencies
  changed_when: False

- debug:
    var: drush_dl_drulenium_dependencies


- name: Enable Diff Number Libraries via Drush
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: drush @hostmaster en diff number libraries taxonomy -y
  register: drush_dl_drulenium_dependencies_enabled
  changed_when: False

- debug:
    var: drush_dl_drulenium_dependencies_enabled

#- name: Check
#  stat: path=/etc/shorewall/rules
#  register: shorewall_rules

- name: Get PHP Web Driver
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: wget https://github.com/facebook/php-webdriver/archive/master.zip -O /var/aegir/hostmaster-{{ aegir_platform_version }}/sites/all/libraries/master.zip
  register: drush_wget_php_web_driver
  changed_when: False

#- name: Get PHP Web Driver
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  shell: wget https://github.com/facebook/php-webdriver/archive/master.zip -O /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/master.zip
#  register: drush_wget_php_web_driver
#  changed_when: False

#- debug:
#    var: drush_wget_php_web_driver

# unarchive doesnt work on Ansible 1.9
#- unarchive: src=https://github.com/facebook/php-webdriver/archive/master.zip dest=/var/aegir/hostmaster-7.x-3.x/sites/all/libraries copy=no
#  changed_when: False

- name: Unzip PHP Web Driver
  sudo: True
  sudo_user: "{{ aegir_user }}"
  shell: unzip -d /var/aegir/hostmaster-{{ aegir_platform_version }}/sites/all/libraries
  ignore_errors: yes

- name: Check PHP Web Driver
  stat: path=/var/aegir/hostmaster-{{ aegir_platform_version }}/sites/all/libraries/selenium_webdriver
  register: check_web_driver

#- name: Move PHP Web Driver
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  register: move_php_web_driver
#  shell: mv /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/php-webdriver-master /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver
#  ignore_errors: yes


- name: Move php-webdriver-master to selenium_webdriver
  sudo: True
  sudo_user: "{{ aegir_user }}"
  command: mv /var/aegir/hostmaster-{{ aegir_platform_version }}/sites/all/libraries/php-webdriver-master/ /var/aegir/hostmaster-{{ aegir_platform_version }}/sites/all/libraries/selenium_webdriver creates="/var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver" removes="/var/aegir/hostmaster-7.x-3.x/sites/all/libraries/php-webdriver-master"
#  command: mv /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/php-webdriver-master/ /var/aegir/hostmaster-7.x-3.x/sites/all/libraries/selenium_webdriver
  changed_when: False

#  when: foo_stat.stat.exists

  #when: check_web_driver.rc != 1

- name: Switch to aegir and download Hosting Drulenium
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valkyrie_modules_enabled
  shell: drush @hostmaster dl drulenium-1.0-beta22 -y
  changed_when: False


## vset Drulenium settings for Ubuntu 14 or via Feature?

- name: Drush | Drush Download Hosting Drulenium
  sudo: True
  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
  command: >
    drush @hostmaster dl hosting_drulenium-3.0-alpha2 -y
  register: drush_dl_hosting_drulenium
#  changed_when: "'hosting_drulenium already exists. Do you want to overwrite it? (y/n): y' in drush_dl_hosting_drulenium.stdout"
#  failed_when: "'already installed' not in drush_dl_hosting_drulenium.stdout and 'install ok' not in drush_dl_hosting_drulenium.stdout and drush_dl_hosting_drulenium.stderr"
  changed_when: False


- debug:
    var: drush_dl_drulenium_dependencies_enabled

- name: Switch to aegir and enable Drulenium
  sudo: True
  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
  shell: drush @hostmaster en drulenium -y
  changed_when: False

- name: Switch to aegir and enable Hosting Drulenium
  sudo: True
  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
  shell: drush @hostmaster en hosting_drulenium -y
  changed_when: False

- name: clear cache - drush cc drush
  sudo: True
  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
  shell: drush cc drush
  changed_when: False

## TODO add handlers

- name: clear cache - drush cc all
  sudo: True
  sudo_user: "{{ aegir_user }}"
#  register: valkyrie_modules_enabled
  shell: drush cc all
  changed_when: False

#- name: drush @hostmaster hosting-tasks --debug
#  sudo: True
#  sudo_user: "{{ aegir_user }}"
#  changed_when: False

#  register: valkyrie_modules_enabled
#  shell: drush @hostmaster hosting-tasks --debug
